name: Setup Python and Poetry

inputs:
  python-version:
    required: true
    description: "Python version"
  poetry-version:
    required: true
    description: "Poetry version"
  install-dev:
    required: false
    description: "Install development dependencies"
  path:
    required: false
    description: "Relative path where the action should run"

runs:
  using: composite
  steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Load cached dependencies
      id: cached-dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}/.venv
        key: python-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/actions/setup-python-poetry/action.yml') }}

    - name: Install dependencies
      working-directory: ${{ inputs.path }}
      if: steps.cached-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install --no-interaction --no-root ${{ inputs.install-dev == 'true' && '-E dev' || '' }}

    - name: Install library
      working-directory: ${{ inputs.path }}
      shell: bash
      run: poetry install --no-interaction
