name: CI for Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: ctu-timetable-generator/yarn.lock

      - name: Install packages
        working-directory: ctu-timetable-generator
        run: |
          yarn install --pure-lockfile

      - name: Lint
        working-directory: ctu-timetable-generator
        run: |
          yarn run lint
